source 'https://rubygems.org'

gem 'coffee-rails', '~> 4.0'
gem 'devise'
gem "font-awesome-rails"
gem 'jquery-rails'
gem 'pg', '~> 0.17'
gem 'rails', '4.1.5'
gem 'rails_12factor'
gem 'sass-rails', '~> 4.0.3'
gem 'simple_form'
gem 'turbolinks'
gem 'twitter-bootstrap-rails', '~> 3.0'
gem 'uglifier', '>= 1.3.0'
gem 'will_paginate', '~> 3.0'