development:
  adapter: postgresql
  encoding: unicode
  database: speaker_finder_development
  host: localhost
  pool: 5
  username: postgres
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: speaker_finder_test
  host: localhost
  pool: 5
  username: postgres
  password: root